name: Build Container

on:
    workflow_dispatch:
    push:
        branches: [ "master" ]
            

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker
              uses: docker/setup-buildx-action@v3

            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/lantern-cloud-services/max-object-detectoer
                tags: |
                  type=sha,format=long,value=${GITHUB_SHA}
                  type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: your-docker-username/your-docker-repo:latest

            - name: Sign in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                username: ${{ github.actor }}
                password: ${{ github.token }}
                registry: ghcr.io
        
            - name: Build and push Docker image
              id: container_build_and_push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: Dockerfile
                tags: ${{ steps.meta.outputs.tags }}
                push: true